### ISSUE TITLE
Track found words and reject duplicate entries

### ISSUE THREAD

**Issue by Alchus** [Alchus/assembly#5]

**Comment by Alchus** [comment]
See comments in code at the label "inList"

**Comment by 7alman** [comment]
I finished this. Just gotta put it up on here, having trouble with it, it keeps rejecting it.

**Comment by 7alman** [comment]
I did a force push because it kept rejecting me when I was trying to push my code. It committed all my files and shows me as the only contributor. You can push your local repo if you want and I'll try pushing it again when i see you in class in a couple of hours.
